openapi: 3.2.0
info:
  title: Lemon Squeezy Invoices API
  description: '

    Welcome to Lemon Squeezy! Whether you''re launching a brand new store, a

    newsletter, or you''re interested in using Lemon Squeezy as your ecommerce

    platform, you can find everything you need to know here.'
  version: 1.0.0
servers:
- url: https://api.lemonsqueezy.com
security:
- bearerAuth: []
tags:
- name: Invoices
paths:
  /v1/subscription-invoices/1:
    get:
      tags:
      - Invoices
      summary: Lemon Squeezy Retrieve a subscription invoice
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/subscription-invoices:
    get:
      tags:
      - Invoices
      summary: Lemon Squeezy List all subscription invoices
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
