openapi: 3.2.0
info:
  title: Lemon Squeezy Redemptions API
  description: '

    Welcome to Lemon Squeezy! Whether you''re launching a brand new store, a

    newsletter, or you''re interested in using Lemon Squeezy as your ecommerce

    platform, you can find everything you need to know here.'
  version: 1.0.0
servers:
- url: https://api.lemonsqueezy.com
security:
- bearerAuth: []
tags:
- name: Redemptions
paths:
  /v1/discount-redemptions/1:
    get:
      tags:
      - Redemptions
      summary: Lemon Squeezy Retrieve a discount redemption
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/discount-redemptions:
    get:
      tags:
      - Redemptions
      summary: Lemon Squeezy List all discount redemptions
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
