openapi: 3.2.0
info:
  title: Lemon Squeezy Users API
  description: '

    Welcome to Lemon Squeezy! Whether you''re launching a brand new store, a

    newsletter, or you''re interested in using Lemon Squeezy as your ecommerce

    platform, you can find everything you need to know here.'
  version: 1.0.0
servers:
- url: https://api.lemonsqueezy.com
security:
- bearerAuth: []
tags:
- name: Users
paths:
  /v1/users/me:
    get:
      tags:
      - Users
      summary: Lemon Squeezy Retrieve the authenticated user
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
