openapi: 3.2.0
info:
  title: Lemon Squeezy License API
  description: '

    Welcome to Lemon Squeezy! Whether you''re launching a brand new store, a

    newsletter, or you''re interested in using Lemon Squeezy as your ecommerce

    platform, you can find everything you need to know here.'
  version: 1.0.0
servers:
- url: https://api.lemonsqueezy.com
security:
- bearerAuth: []
tags:
- name: License
paths:
  /v1/license-keys/1:
    get:
      tags:
      - License
      summary: Lemon Squeezy Retrieve a license key
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/license-keys:
    get:
      tags:
      - License
      summary: Lemon Squeezy List all license keys
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/license-key-instances/1:
    get:
      tags:
      - License
      summary: Lemon Squeezy Retrieve a license key instance
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/license-key-instances:
    get:
      tags:
      - License
      summary: Lemon Squeezy List all license key instances
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
