openapi: 3.0.0
info:
  title: Lemon Squeezy 7c41 Files API
  description: '

    Welcome to Lemon Squeezy! Whether you''re launching a brand new store, a

    newsletter, or you''re interested in using Lemon Squeezy as your ecommerce

    platform, you can find everything you need to know here.'
  version: 1.0.0
servers:
- url: https://api.lemonsqueezy.com
security:
- bearerAuth: []
tags:
- name: Files
paths:
  /v1/files/1:
    get:
      tags:
      - Files
      summary: Lemon Squeezy Retrieve a file
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/files:
    get:
      tags:
      - Files
      summary: Lemon Squeezy List all files
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
