openapi: 3.0.0
info:
  title: Lemon Squeezy License API
  description: >-
    ## Step 1: Fork this collection


    [![](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/24909116-16bc36f7-5cc6-4131-9269-5ee1cb0c2380?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D24909116-16bc36f7-5cc6-4131-9269-5ee1cb0c2380%26entityType%3Dcollection%26workspaceId%3D5d229114-c0b1-40ec-8bab-f171fbda8aaf)


    ## Step 2: Make your first API call


    Follow our [API
    documentation](https://docs.lemonsqueezy.com/help/licensing/license-api) to
    make your first API call.
  version: 1.0.0
servers:
  - url: http://{{api_url}}
paths:
  /v1/licenses/activate:
    post:
      tags:
        - default
      summary: Activate a license key
      description: Activate a license key and receive an instance ID in return.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                license_key:
                  type: string
                  description: The license key
                instance_name:
                  type: string
                  description: A label for the new instance to identify it in Lemon Squeezy
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/licenses/validate:
    post:
      tags:
        - default
      summary: Validate a license key
      description: Validate a license key or license key instance.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                license_key:
                  type: string
                  description: The license key
                instance_id:
                  type: string
                  description: >-
                    If included, validate a license key instance, otherwise a
                    license key. If no `instance_id` is provided, the response
                    will contain `"instance": null`.
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/licenses/deactivate:
    post:
      tags:
        - default
      summary: Deactivate a license key instance
      description: Deactivate a license key instance.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                license_key:
                  type: string
                  description: The license key
                instance_id:
                  type: string
                  description: The instance ID returned when activating a license key
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
